language: node_js

sudo: false

node_js:
  - 12

env:
  global:
    - ENV_BUCKET_NAME=wdraktuell-bot-tg-env
    - AWS_REGION=eu-central-1

cache: yarn

before_script:
  - ./config/prepare-ci.js

script: echo "No tests yet :/"

deploy:
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=staging && yarn serverless create_domain && yarn serverless deploy && ./setWebhook.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=prod && yarn serverless create_domain && yarn serverless deploy
    on:
      branch: production

notifications:
  slack:
    rooms:
      - secure: X4jWgFCKotxEYbdF5XupnoJ6PMhDXs0VQ4w6Yr6TUeSasCy6ZoTKI9sRevaguhta9GwVliKTp15eGXVylOYHCpE+zEaDuOWmamRWBIMhtro/tD8rgfHnlnXopmGbUDA/wauWpvkKNM7RguTf9g5wH5QD0rz2cjJQX7NqnNzPA+VAXfBwzk0Crcg1K3qFli+xGDMx6+Vv0Q2Jto4xh114LEAmgpLe3LTwZDpdWSzQcqodBXg+2QFrmbErxvcZHyDOzdplOjwg8F620782sW7smXrqzPc5ZWa7u2ZSZ/yJWl/FTVNrnKjuYa29TKxrGEClpDVvRN/Jwk6qIOFkVD0reqnj7XgUyXDn6iXHMMWcpRqxZcu9WseO683mkKcHeEjEnur60kn/WGAKdzmYkT4cIGgqekKClL2apVGd2IImvuoysHdNt7nOM2+IyyPcqPUrJbpK418fmwcWX8BlMrWyOWNvpSpXZCfOWVzQxzkSKLO5lafZPtCOIuW9VtLHIkg/IwDbiJWgwGARjLE+crzNa/5WeNkfdACG4f3N5vcCuTjpb/IB4Ix6rjYAhXPx2TE47fECM68L+WmDMioYi+TFEzs8ioqaKck6UEh70/rBQCN8FCk1QQ8JTeCjYYhtKw5fSxHRaoy0kOVAstXytwqEUE+WVEJK7PEcakvgLsb1BG8=
    on_pull_requests: false
    template:
      - "Deployment %{result}:"
      - "<%{compare_url}|%{repository_slug}:%{branch}#%{commit}> by %{author}"
