language: node_js

sudo: false

node_js:
  - 12

env:
  global:
    - ENV_BUCKET_NAME=wdraktuell-bot-tg-env
    - AWS_REGION=eu-central-1

cache: yarn

before_script:
  - ./config/prepare-ci.js

script: echo "No tests yet :/"

deploy:
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=staging && yarn serverless create_domain && yarn serverless deploy && ./setWebhook.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=prod && yarn serverless create_domain && yarn serverless deploy
    on:
      branch: production

notifications:
  slack:
    rooms:
    - secure: mJNBC6+NONJqQTx//pc8+J+WWPRFnCBm8Xj+FBeQnR50Qu63wATDCSioBYv84A82RlXfoaTpArafEXRqpA0Jsk7QNWaBWu81IIv26gpqdou5iexmTVsqHEc1S4ztnvJmayZ6bq1wFZ3vyobSIi/vKaYzZQQ5g6gaAHEfdURehupJCrUkdHFG5Uwt4PCCIZSFpwLP2a3zDw5fHUI6PIWUkTkHAtXwXMMsRXgsCuh2sYApOX4ZE0ARze+q7xI55vkxuyxMUXNm/hyfd/rx0P2K48Yzr/5EOxlqRBVl84K8y4ofBDsOFTUHEyHHTL+s2ud85yWy9Kislb/YWXPjX+bUsbV+hAFDQB/1tI88ErnwbGPJN6d+o6GsPWc82297nDXVE8xj0Iebi87ZbVocikIGrzrjXumLyYyBBz9AwnlOVHEDD9tlO7D5iaWCxh7IMu1zfAHgIWoEzVSaRs5OOm+nJooesuStzB7xF5SYROlGJgnLZlI29H46xY7uzGVcfjhpIzJtVuFW2JR1ug+8uEsgISnF/7yuRA9Oaab7jExniR0JKnJFV1+ieIUTPbuW/4fQD0gtGCYxCz8q5u3L8KhfslV5WgYzXGHZw7Rm402VlBdK8xlTx1UWFrlWaYvAPVJRYDNfytL+5h8w5LP44WqsZBJ0zC3nTkSaKixxojKOGdM=
    on_pull_requests: false
    template:
      - "Deployment %{result}:"
      - "<%{compare_url}|%{repository_slug}:%{branch}#%{commit}> by %{author}"
